// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver');
const assert = require('assert');

'use strict';

let jsonData = require('../constants.json');

console.log(jsonData);

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

(async function example() {
  let driver = await new Builder().forBrowser('firefox').build();
  try {
		
    await driver.get("http://"+jsonData.user_basic+":"+jsonData.pass_basic+"@"+jsonData.ip+"/")
    //await driver.get("http://192.168.137.14/")

    await sleep(4000);
    await driver.manage().window().setRect(1920, 926)
    await (await driver.wait(until.elementLocated(By.xpath("//ul[@id='navbar_header']/li/a/i")),20000)).click();
    await (await driver.wait(until.elementLocated(By.xpath("//div[@id='control-sidebar-home-tab']/ul[2]/li[2]/a/div/h3/span")),20000)).click();
    await sleep(3000);






    await (await driver.wait(until.elementLocated(By.xpath("/html/body/div/div[1]/section[2]/div[2]/section[2]/div/div[2]/div/table/tbody/tr[2]/td[3]")),20000)).click()
    await sleep(9000);

  } finally {
    await driver.quit();
  }
})();
