// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver');
const assert = require('assert');

'use strict';

let jsonData = require('../constants.json');

console.log(jsonData);

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

(async function example() {
  let driver = await new Builder().forBrowser('firefox').build();
  try {
		
    await driver.get("http://"+jsonData.user_basic+":"+jsonData.pass_basic+"@"+jsonData.ip+"/")
    //await driver.get("http://192.168.137.14/")
    
    await driver.manage().window().setRect(1920, 926)
    
    await (await driver.wait(until.elementLocated(By.id("max_em")),20000)).click()

    await (await driver.wait(until.elementLocated(By.xpath("//div[@id='box_ifaceConfig_vlan_10']/div/div/span/button[2]/i")),20000)).click()

    await sleep(2000);
    assert(await driver.switchTo().alert().getText() == "Are you sure you want to delete this VLAN port (vlan_10)?")
    await driver.switchTo().alert().accept()


  } finally {
    await driver.quit();
  }
})();
