// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver');
const assert = require('assert');

'use strict';

let jsonData = require('../constants.json');

console.log(jsonData);

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

(async function example() {
  let driver = await new Builder().forBrowser('firefox').build();
  try {

    
		//console.log(jsonData.pathUploadFile)
    await driver.get("http://"+jsonData.user_basic+":"+jsonData.pass_basic+"@"+jsonData.ip+"/")
    //await driver.get("http://192.168.137.14/")
    await sleep(4000);
    await driver.manage().window().setRect(1920, 926)
    await (await driver.wait(until.elementLocated(By.xpath("//ul[@id='navbar_header']/li/a/i")),20000)).click();
    await (await driver.wait(until.elementLocated(By.xpath("//div[@id='control-sidebar-home-tab']/ul[2]/li[2]/a/div/h3/span")),20000)).click();
    await sleep(3000);
    await (await driver.wait(until.elementLocated(By.id("configName")),20000)).click()
    await driver.findElement(By.id("configName")).sendKeys("config_1")
  
    await driver.findElement(By.id("btn-up2")).click()
    await driver.wait(until.alertIsPresent());
    await sleep(2000)
    assert(await driver.switchTo().alert().getText() == "Save completed successfully")
    await driver.switchTo().alert().accept()        
  
   
    await sleep(10000);


    await (await driver.wait(until.elementLocated(By.xpath('//*[@id="max_em"]')),20000)).click();
    //await (await driver.wait(until.elementLocated(By.xpath("//table[@id='table_sfpConfig_0']/tbody/tr[5]/td[2]/select")),20000)).click();
    
    await (await driver.wait(until.elementLocated(By.id("dns1")),20000)).click()
    await driver.findElement(By.id("dns1")).clear()
    await driver.findElement(By.id("dns1")).sendKeys("8.8.8.15")
    await sleep(2000)
    //driver.findElement(By.xpath("/html/body/div/div[1]/section[1]/h1/span[3]/button[2]")).click();
    await driver.findElement(By.css("#where-right2 > button:nth-child(2)")).click()
    await driver.wait(until.alertIsPresent());
    await sleep(2000)
    assert(await driver.switchTo().alert().getText() == "Changes successfully applied.")
    await driver.switchTo().alert().accept()  
    await sleep(10000)


    await (await driver.wait(until.elementLocated(By.xpath("//ul[@id='navbar_header']/li/a/i")),20000)).click();
    await (await driver.wait(until.elementLocated(By.xpath("//div[@id='control-sidebar-home-tab']/ul[2]/li[2]/a/div/h3/span")),20000)).click();
    await sleep(3000);
    await (await driver.wait(until.elementLocated(By.id("configName")),20000)).click()
    await driver.findElement(By.id("configName")).sendKeys("config_2")

    await driver.findElement(By.id("btn-up2")).click()
    await driver.wait(until.alertIsPresent());
    await sleep(2000)
    assert(await driver.switchTo().alert().getText() == "Save completed successfully")
    await driver.switchTo().alert().accept()        
    await sleep(10000)  

    await (await driver.wait(until.elementLocated(By.xpath("/html/body/div/div[1]/section[2]/div[2]/section[2]/div/div[2]/div/table/tbody/tr[3]/td[4]/i")),20000)).click();
   

    await (await driver.wait(until.elementLocated(By.xpath("/html/body/div/div[1]/section[2]/div[2]/section[2]/div/div[2]/div/table/tbody/tr[4]/td[4]/i")),20000)).click();
    await sleep(10000)
    await (await driver.wait(until.elementLocated(By.xpath("/html/body/div/div[1]/section[2]/div[2]/section[2]/div/div[2]/div/table/tbody/tr[4]/td[5]")),20000)).click();
    await driver.wait(until.alertIsPresent());
    await sleep(2000)
    await driver.switchTo().alert().accept()    
    await driver.wait(until.alertIsPresent());
    await sleep(2000)
    await driver.switchTo().alert().accept()     
    await sleep(5000)   



    await (await driver.wait(until.elementLocated(By.xpath('//*[@id="max_em"]')),20000)).click();
    //await (await driver.wait(until.elementLocated(By.xpath("//table[@id='table_sfpConfig_0']/tbody/tr[5]/td[2]/select")),20000)).click();
    
    await (await driver.wait(until.elementLocated(By.id("dns1")),20000)).click()
    await driver.findElement(By.id("dns1")).clear()
    await driver.findElement(By.id("dns1")).sendKeys("8.8.8.16")
    await sleep(2000)
    //driver.findElement(By.xpath("/html/body/div/div[1]/section[1]/h1/span[3]/button[2]")).click();
    await driver.findElement(By.css("#where-right2 > button:nth-child(2)")).click()
    await driver.wait(until.alertIsPresent());
    await sleep(2000)
    assert(await driver.switchTo().alert().getText() == "Changes successfully applied.")
    await driver.switchTo().alert().accept()  
    await sleep(10000)  

    await (await driver.wait(until.elementLocated(By.xpath("//ul[@id='navbar_header']/li/a/i")),20000)).click();
    await (await driver.wait(until.elementLocated(By.xpath("//div[@id='control-sidebar-home-tab']/ul[2]/li[2]/a/div/h3/span")),20000)).click();
    await sleep(3000);
    await (await driver.wait(until.elementLocated(By.id("configName")),20000)).click()
    await driver.findElement(By.id("configName")).sendKeys("config_3")

    await driver.findElement(By.id("btn-up2")).click()
    await driver.wait(until.alertIsPresent());
    await sleep(2000)
    assert(await driver.switchTo().alert().getText() == "Save completed successfully")
    await driver.switchTo().alert().accept()        
    await sleep(10000)  
    
    await driver.findElement(By.id("fileToUpload")).sendKeys(jsonData.pathUploadFile)
    await sleep(2000)
    await driver.findElement(By.id("btn-up")).click()
    await sleep(9000);
    assert(await driver.switchTo().alert().getText() == "Do want to apply the loaded configuration?")
    await driver.switchTo().alert().accept()
    await driver.wait(until.alertIsPresent());
    await sleep(2000)
    await driver.switchTo().alert().accept()     
    await sleep(60000)
    await (await driver.wait(until.elementLocated(By.id("logo")),20000)).click();
    await (await driver.wait(until.elementLocated(By.xpath("//ul[@id='navbar_header']/li/a/i")),20000)).click();
    await (await driver.wait(until.elementLocated(By.xpath("//div[@id='control-sidebar-home-tab']/ul[2]/li[2]/a/div/h3/span")),20000)).click();
    await sleep(3000);

    await (await driver.wait(until.elementLocated(By.xpath("/html/body/div/div[1]/section[2]/div[2]/section[2]/div/div[2]/div/table/tbody/tr[3]/td[5]")),600000)).click();
    await driver.wait(until.alertIsPresent());
    await sleep(2000)
    await driver.switchTo().alert().accept()    
    await driver.wait(until.alertIsPresent());
    await sleep(2000)
    await driver.switchTo().alert().accept()     
    await sleep(5000) 

    await (await driver.wait(until.elementLocated(By.xpath("/html/body/div/div[1]/section[2]/div[2]/section[2]/div/div[2]/div/table/tbody/tr[3]/td[5]")),20000)).click();
    await driver.wait(until.alertIsPresent());
    await sleep(2000)
    await driver.switchTo().alert().accept()    
    await driver.wait(until.alertIsPresent());
    await sleep(2000)
    await driver.switchTo().alert().accept()     
    await sleep(5000) 

    await (await driver.wait(until.elementLocated(By.xpath("/html/body/div/div[1]/section[2]/div[2]/section[2]/div/div[2]/div/table/tbody/tr[3]/td[5]")),20000)).click();
    await driver.wait(until.alertIsPresent());
    await sleep(2000)
    await driver.switchTo().alert().accept()    
    await driver.wait(until.alertIsPresent());
    await sleep(2000)
    await driver.switchTo().alert().accept()     
    await sleep(5000) 




   
  } finally {
    await driver.quit();
  }
})();
