// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver');
const assert = require('assert');

'use strict';

let jsonData = require('../constants.json');

console.log(jsonData);

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

(async function example() {
  let driver = await new Builder().forBrowser('firefox').build();
  try {
    const ip_test = "192.168.10.64"
    const netmask_test = "255.255.255.0"
    const gateway_test = "192.168.2.1"
    const dns1_test = "8.8.8.8"
    const dns2_test = "8.8.4.4"
		
    await driver.get("http://"+jsonData.user_basic+":"+jsonData.pass_basic+"@"+jsonData.ip+"/")
    //await driver.get("http://192.168.137.14/")

    await driver.manage().window().setRect(1920, 926)
    await (await driver.wait(until.elementLocated(By.id("max_em")),20000)).click()



    await (await driver.wait(until.elementLocated(By.css(".btn-a:nth-child(1)")),20000)).click()

    await (await driver.wait(until.elementLocated(By.id("virtualIfaceName")),20000)).click()
    await driver.findElement(By.id("virtualIfaceName")).sendKeys("vlan_10")

    await driver.findElement(By.id("vlan")).click()
    await driver.findElement(By.id("vlan")).sendKeys("10")
    //await sleep (20000)
    await driver.findElement(By.id("ifaceName")).click()
    {
      const dropdown = await driver.findElement(By.id("ifaceName"))
      await dropdown.findElement(By.xpath("/html/body/div[1]/div[1]/section[2]/div[2]/section/div/div[2]/div/table/tbody/tr[2]/td[2]/select/option[3]")).click()
    }
  
  
    await driver.findElement(By.xpath("/html/body/div[1]/div[1]/section[2]/div[2]/section/div/div[2]/div/table/tbody/tr[6]/td[2]")).click()
    {
      const dropdown = await driver.findElement(By.xpath("/html/body/div[1]/div[1]/section[2]/div[2]/section/div/div[2]/div/table/tbody/tr[6]/td[2]"))
      await dropdown.findElement(By.xpath("/html/body/div[1]/div[1]/section[2]/div[2]/section/div/div[2]/div/table/tbody/tr[6]/td[2]/select/option[3]")).click()
    }
   
    
  
   

    await driver.findElement(By.xpath("//table[@id='table_newVlanEntry_0']/tbody/tr[7]/td[2]/input")).click();
    await driver.findElement(By.xpath("//table[@id='table_newVlanEntry_0']/tbody/tr[7]/td[2]/input")).clear();
    await driver.findElement(By.xpath("//table[@id='table_newVlanEntry_0']/tbody/tr[7]/td[2]/input")).sendKeys(ip_test);
    await driver.findElement(By.xpath("//table[@id='table_newVlanEntry_0']/tbody/tr[8]/td[2]/input")).clear();
    await driver.findElement(By.xpath("//table[@id='table_newVlanEntry_0']/tbody/tr[8]/td[2]/input")).sendKeys(netmask_test);
    await driver.findElement(By.xpath("//table[@id='table_newVlanEntry_0']/tbody/tr[9]/td[2]/input")).clear();
    await driver.findElement(By.xpath("//table[@id='table_newVlanEntry_0']/tbody/tr[9]/td[2]/input")).sendKeys(gateway_test);
    await driver.findElement(By.xpath("//table[@id='table_newVlanEntry_0']/tbody/tr[10]/td[2]/input")).clear();
    await driver.findElement(By.xpath("//table[@id='table_newVlanEntry_0']/tbody/tr[10]/td[2]/input")).sendKeys(dns1_test);
    await driver.findElement(By.xpath("//table[@id='table_newVlanEntry_0']/tbody/tr[11]/td[2]/input")).clear();
    await driver.findElement(By.xpath("//table[@id='table_newVlanEntry_0']/tbody/tr[11]/td[2]/input")).sendKeys(dns2_test);    

    driver.findElement(By.id("btn-up-vlan")).click();
    
    await sleep(2000);
    await driver.wait(until.alertIsPresent());
    await sleep(2000);
    assert(await driver.switchTo().alert().getText() == "Changes successfully applied.")
    await driver.switchTo().alert().accept()  
  } finally {
    await driver.quit();
  }
})();
