// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver');
const assert = require('assert');

'use strict';

let jsonData = require('../constants.json');

console.log(jsonData);

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

(async function example() {
  let driver = await new Builder().forBrowser('firefox').build();
  try {
		
    await driver.get("http://"+jsonData.user_basic+":"+jsonData.pass_basic+"@"+jsonData.ip+"/")
    //await driver.get("http://192.168.137.14/")
    
    await driver.manage().window().setRect(1920, 926)
    
    await (await driver.wait(until.elementLocated(By.id("max_em")),20000)).click()


    await (await driver.wait(until.elementLocated(By.id("hostname")),20000)).click()
    await driver.findElement(By.id("hostname")).clear()
    await driver.findElement(By.id("hostname")).sendKeys("relyTsnBridgeTest")
    
    await driver.findElement(By.css(".btn-a:nth-child(2)")).click()
    await sleep(20000);
    assert(await driver.switchTo().alert().getText() == "Changes successfully applied.")
    await driver.switchTo().alert().accept()      
  } finally {
    await driver.quit();
  }
})();
