// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver');
const assert = require('assert');

'use strict';

let jsonData = require('../constants.json');

console.log(jsonData);

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

(async function example() {

  var webVersion = "new"

  let driver = await new Builder().forBrowser('firefox').build();
  try {
		
      //***********************************
      //const new_password = "passwordtest"
      //const new_password = "sys-admin"
      const new_password = "sys-operator"
      //const new_password = "relyum"
      //***********************************


      await driver.get("http://"+jsonData.user_admin+":"+jsonData.pass_admin+"@"+jsonData.ip+"/advanced.html")

      await (await driver.wait(until.elementLocated(By.css(".gear-right > a")),40000)).click()
      await sleep(2000)

      if (webVersion=="new"){
        await driver.findElement(By.xpath("//span[.='Security']")).click()
      } else {
        await driver.findElement(By.id("tr_rg")).click()
      }      
      
      if (webVersion=="new"){
        await (await driver.wait(until.elementLocated(By.id("user")),20000)).click()
        {
          await sleep(2000)
          const dropdown = await driver.findElement(By.id("user"))
          await dropdown.findElement(By.xpath("//select[@id='user']/option[. = 'Basic user (sys-operator)']")).click()
          //await dropdown.findElement(By.xpath("//select[@id='user']/option[. = 'Advanced user (sys-admin)']")).click()
        }   
        await driver.findElement(By.id("password")).sendKeys(new_password)
        await driver.findElement(By.id("newPassword")).sendKeys(new_password) 
        console.log("The new password is: "+new_password);
        await driver.findElement(By.id("where-right2")).click() 
        //assert(await driver.switchTo().alert().getText() == "Changes successfully applied.")    
        //await driver.switchTo().alert().accept()     
        await (await driver.wait(until.elementLocated(By.css(".gear-right > a")),4000)).click()
        await (await driver.wait(until.elementLocated(By.xpath("//span[.='Logout']")),4000)).click()
    
        //await (await driver.wait(until.elementLocated(By.css(".btn-danger")),4000)).click()  

      } else {

        await (await driver.wait(until.elementLocated(By.id("pass-one")),4000)).click()

        await driver.findElement(By.id("pass-one")).sendKeys(new_password)
        await driver.findElement(By.id("pass-two")).sendKeys(new_password)
        await driver.findElement(By.id("sender")).click()
        assert(await driver.switchTo().alert().getText() == "Password correctly updated\nYou may need to reload the page to see the changes")
    
        //await sleep(2000);
        console.log("The new password is: "+new_password);
        await driver.switchTo().alert().accept()
    
        await (await driver.wait(until.elementLocated(By.css(".gear-right > a")),4000)).click()
        await (await driver.wait(until.elementLocated(By.id("tr_rx")),4000)).click()
    
        await (await driver.wait(until.elementLocated(By.css(".btn-danger")),4000)).click()             
      }    
  } finally {
    await driver.quit();
  }
})();
