// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver');
const assert = require('assert');

'use strict';

let jsonData = require('../constants.json');

console.log(jsonData);

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

(async function example() {
  let driver = await new Builder().forBrowser('firefox').build();
  try {
		
    await driver.get("http://"+jsonData.user_basic+":"+jsonData.pass_basic+"@"+jsonData.ip+"/")
    //await driver.get("http://192.168.137.14/")
    

    await driver.manage().window().setRect(1920, 926)
    await (await driver.wait(until.elementLocated(By.id("max_em")),20000)).click()

    await (await driver.wait(until.elementLocated(By.id("IPv4")),20000)).click()
    {
      const dropdown = await driver.findElement(By.id("addrType"))
      await dropdown.findElement(By.xpath("/html/body/div[1]/div[1]/section[2]/div[2]/div/section[1]/div[1]/div[2]/div/table/tbody/tr[4]/td[2]/select/option[4]")).click()
    }
    await driver.findElement(By.css("#where-right2 > button:nth-child(2)")).click()
    await driver.wait(until.alertIsPresent());
    await sleep(2000);
    assert(await driver.switchTo().alert().getText() == "Changes successfully applied.")
    await driver.switchTo().alert().accept()   
  } finally {
    await driver.quit();
  }
})();
